"""Documentation for backend/apps/orders/migrations/0003_alter_order_total.py."""

# Generated by Django 4.2.8 on 2026-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    """Represents the Migration class in this module."""

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
